# Generated by Django 4.1.1 on 2022-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
